version: '3'

services:
  controller:
    image: dtr.corp.appdynamics.com/appdynamics/enterprise-console:latest
    container_name: controller
    ports:
      - "8080:8080"
      - "9080:9080"
      - "9200:9200"
  machine:
    container_name: machine
    environment:
     - APPDYNAMICS_AGENT_ACCOUNT_NAME=customer1
     - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=SJ5b2m7d1$$354
     - APPDYNAMICS_CONTROLLER_HOST_NAME=controller
     - APPDYNAMICS_CONTROLLER_SSL_ENABLED=false
     - APPDYNAMICS_CONTROLLER_PORT=8080
     - MACHINE_AGENT_PROPERTIES=-Dappdynamics.agent.uniqueHostId=azureTest -Dappdynamics.sim.enabled=true -Dappdynamics.docker.enabled=false
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /:/hostroot:ro
      - /var/run/docker.sock:/var/run/docker.sock